version: '3'
services:
  suglider-auth:
    container_name: suglider-auth
    image: ghcr.io/winds6206/suglider-auth
    restart: unless-stopped
    tty: true
    stdin_open: true
    entrypoint:
      - /usr/local/app/bin/suglider-auth
      - -config=/tmp/config.toml
      - -debug=true
    environment:
      ENV: dev
      # SWAGGER_OFF: Y
      GIN_MODE: release
    volumes:
      - ./test/config.toml:/tmp/config.toml:ro
    networks:
      - "suglider-auth"
    ports:
      - 9527:9527
    ulimits:
      nproc: 65535
      nofile:
        soft: 10240
        hard: 65536
networks:
  suglider-auth:
    name: suglider-auth
    driver: bridge
