version: '3'
services:
  suglider-auth:
    container_name: suglider-auth
    image: ghcr.io/winds6206/suglider-auth
    restart: unless-stopped
    tty: true
    stdin_open: true
    entrypoint:
      - /usr/local/app/bin/suglider-auth
      - -config=/tmp/config.toml
      - -debug=true
    environment:
      ENV: dev
      # DISABLE_SWAGGER: Y
      GIN_MODE: release
    volumes:
      - ./test/config.toml:/tmp/config.toml:ro
    networks:
      - "suglider-auth"
    ports:
      - 9527:9527
    ulimits:
      nproc: 65535
      nofile:
        soft: 10240
        hard: 65536
  suglider-auth-db:
    container_name: suglider-auth-db
    image: mariadb:11
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      TZ: "Asia/Taipei"
      MARIADB_ROOT_PASSWORD: "YOUR_PASSWORD"
      MARIADB_DATABASE: "suglider"
      MARIADB_USER: "suglider"
      MARIADB_PASSWORD: "YOUR_PASSWORD"
    networks:
      - "suglider-auth"
    ports:
      - 3306:3306
    ulimits:
      nproc: 65535
      nofile:
        soft: 10240
        hard: 65536
networks:
  suglider-auth:
    name: suglider-auth
    driver: bridge
